# Generated by Django 5.1.7 on 2025-03-08 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0003_rename_telefono_personalinfo_sexo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investigacion',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investigaciones', to='scraping.entry'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='entry',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personal_info', to='scraping.entry'),
        ),
    ]
