# Generated by Django 5.1.7 on 2025-05-04 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0004_alter_investigacion_entry_alter_personalinfo_entry'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperienciaProfesional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institucion', models.CharField(max_length=255)),
                ('cargo', models.CharField(max_length=255)),
                ('desde', models.CharField(blank=True, max_length=100, null=True)),
                ('hasta', models.CharField(blank=True, max_length=100, null=True)),
                ('entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='experiencia_profesional', to='scraping.entry')),
            ],
        ),
        migrations.CreateModel(
            name='FormacionAcademica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(max_length=255)),
                ('institucion', models.CharField(max_length=255)),
                ('entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='formacion_academica', to='scraping.entry')),
            ],
        ),
    ]
